package carrera;

public class Principal {

	public static void main(String[] args) {
		Carrera carrera = new Carrera();
		Participante participante1 = new Participante(null);
		Participante[] miembros1 = new Participante[10];
		Equipo equipo1 = new Equipo(miembros1, "Rockets");
		carrera.anhadeParticipante(participante1);
		carrera.anhadeEquipo(equipo1);
		carrera.anhadeParticipanteAEquipo(participante1, equipo1);
		Participante participante2 = new Participante(null);
		carrera.anhadeParticipante(participante2);
		carrera.anhadeParticipanteAEquipo(participante2, equipo1);
		Participante participante3 = new Participante(null);
		carrera.anhadeParticipante(participante3);
		carrera.anhadeParticipanteAEquipo(participante3, equipo1);
		Participante participante4 = new Participante(null);
		carrera.anhadeParticipante(participante4);
		carrera.anhadeParticipanteAEquipo(participante4, equipo1);
		Participante participante5 = new Participante(null);
		carrera.anhadeParticipante(participante5);
		carrera.anhadeParticipanteAEquipo(participante5, equipo1);
		Participante participante6 = new Participante(null);
		carrera.anhadeParticipante(participante6);
		carrera.anhadeParticipanteAEquipo(participante6, equipo1);
		Participante participante7 = new Participante(null);
		carrera.anhadeParticipante(participante7);
		carrera.anhadeParticipanteAEquipo(participante7, equipo1);
		Participante participante8 = new Participante(null);
		carrera.anhadeParticipante(participante8);
		carrera.anhadeParticipanteAEquipo(participante8, equipo1);
		Participante participante9 = new Participante(null);
		carrera.anhadeParticipante(participante9);
		carrera.anhadeParticipanteAEquipo(participante9, equipo1);
		Participante participante10 = new Participante(null);
		carrera.anhadeParticipante(participante10);
		carrera.anhadeParticipanteAEquipo(participante10, equipo1);
		Participante participante1b = new Participante(null);
		Participante[] miembros2 = new Participante[10];
		Equipo equipo2 = new Equipo(miembros2, "Bulls");
		carrera.anhadeParticipante(participante1b);
		carrera.anhadeEquipo(equipo2);
		carrera.anhadeParticipanteAEquipo(participante1b, equipo2);
		Participante participante2b = new Participante(null);
		carrera.anhadeParticipante(participante2b);
		carrera.anhadeParticipanteAEquipo(participante2b, equipo2);
		Participante participante3b = new Participante(null);
		carrera.anhadeParticipante(participante3b);
		carrera.anhadeParticipanteAEquipo(participante3b, equipo2);
		Participante participante4b = new Participante(null);
		carrera.anhadeParticipante(participante4b);
		carrera.anhadeParticipanteAEquipo(participante4b, equipo2);
		Participante participante5b = new Participante(null);
		carrera.anhadeParticipante(participante5b);
		carrera.anhadeParticipanteAEquipo(participante5b, equipo2);
		Participante participante6b = new Participante(null);
		carrera.anhadeParticipante(participante6b);
		carrera.anhadeParticipanteAEquipo(participante6b, equipo2);
		Participante participante7b = new Participante(null);
		carrera.anhadeParticipante(participante7b);
		carrera.anhadeParticipanteAEquipo(participante7b, equipo2);
		Participante participante8b = new Participante(null);
		carrera.anhadeParticipante(participante8b);
		carrera.anhadeParticipanteAEquipo(participante8b, equipo2);
		Participante participante9b = new Participante(null);
		carrera.anhadeParticipante(participante9b);
		carrera.anhadeParticipanteAEquipo(participante9b, equipo2);
		Participante participante10b = new Participante(null);
		carrera.anhadeParticipante(participante10b);
		carrera.anhadeParticipanteAEquipo(participante10b, equipo2);
		carrera.participanteLlegaAMeta(participante1.getNumeroDorsal(), 12.3);
		carrera.participanteLlegaAMeta(participante2.getNumeroDorsal(), 10.3);
		carrera.participanteLlegaAMeta(participante3.getNumeroDorsal(), 12.6);
		carrera.participanteLlegaAMeta(participante4.getNumeroDorsal(), 13.4);
		carrera.participanteLlegaAMeta(participante6.getNumeroDorsal(), 22.3);
		carrera.participanteLlegaAMeta(participante7.getNumeroDorsal(), 9.3);
		carrera.participanteLlegaAMeta(participante5.getNumeroDorsal(), 33.4);
		carrera.participanteLlegaAMeta(participante8.getNumeroDorsal(), 9.3);
		carrera.participanteLlegaAMeta(participante9.getNumeroDorsal(), 11.3);
		carrera.participanteLlegaAMeta(participante10.getNumeroDorsal(), 23.3);
		carrera.participanteLlegaAMeta(participante1b.getNumeroDorsal(), 11.5);
		carrera.participanteLlegaAMeta(participante2b.getNumeroDorsal(), 15.6);
		carrera.participanteLlegaAMeta(participante3b.getNumeroDorsal(), 16.7);
		carrera.participanteLlegaAMeta(participante4b.getNumeroDorsal(), 14.0);
		carrera.participanteLlegaAMeta(participante5b.getNumeroDorsal(), 111.1);
		carrera.participanteLlegaAMeta(participante6b.getNumeroDorsal(), 15.6);
		carrera.participanteLlegaAMeta(participante7b.getNumeroDorsal(), 2.3);
		//carrera.participanteLlegaAMeta(participante8b.getNumeroDorsal(), 15.6);
		//carrera.participanteLlegaAMeta(participante9b.getNumeroDorsal(), 15.6);
		//carrera.participanteLlegaAMeta(participante10b.getNumeroDorsal(), 15.6);
		System.out.println(carrera.muestraLosQueFaltan(equipo2));
		//System.out.println(carrera.muestraClasificacion());
	}

}
